---
name: Renovate

on:
  workflow_call:
    inputs:
      dryRun:
        description: Dry-Run
        default: false
        required: false
        type: string
      logLevel:
        description: Log-Level
        default: debug
        required: false
        type: string
      configurationFile:
        description: Renovate configuration file
        default: .github/renovate.json5
        required: false
        type: string
    secrets:
      app_id:
        description: App ID of the application used to generate a token
        required: true
      app_private_key:
        description: Private key of the application used to generate a token
        required: true

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: tibdex/github-app-token@32691ba7c9e7063bd457bd8f2a5703138591fa58 # v1.9.0
        id: generate-token
        with:
          app_id: ${{ secrets.app_id }}
          private_key: ${{ secrets.app_private_key }}

      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Renovate
        uses: renovatebot/github-action@89c8a9b60f5bc8395658abab8f40f96e4b490ebf # v39.1.0
        env:
          DRY_RUN: ${{ inputs.dryRun }}
          LOG_LEVEL: ${{ inputs.logLevel }}
        with:
          configurationFile: ${{ inputs.configurationFile }}
          token: ${{ steps.generate-token.outputs.token }}
