---
name: Run - Renovate

on:
  workflow_call:
    inputs:
      dryRun:
        description: Dry-Run
        default: false
        required: false
        type: string
      logLevel:
        description: Log-Level
        default: debug
        required: false
        type: string
      version:
        description: Renovate version
        default: latest
        required: false
        type: string
    secrets:
      app_id:
        description: App ID of the application used to generate a token
        required: true
      app_private_key:
        description: Private key of the application used to generate a token
        required: true

env:
  LOG_LEVEL: ${{ inputs.logLevel }}
  RENOVATE_DRY_RUN: ${{ inputs.dryRun }}
  RENOVATE_AUTODISCOVER: true
  RENOVATE_AUTODISCOVER_FILTER: "${{ github.repository }}"
  RENOVATE_PLATFORM: github
  RENOVATE_PLATFORM_COMMIT: true
  RENOVATE_USERNAME: purpose-robot[bot]
  RENOVATE_GIT_AUTHOR: purpose-robot <122760773+purpose-robot[bot]@users.noreply.github.com>
  WORKFLOW_RENOVATE_VERSION: ${{ inputs.version }}

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.app_id }}
          private-key: ${{ secrets.app_private_key }}

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Renovate
        uses: renovatebot/github-action@f9c81dddc9b589e4e6ae0326d1e36f6bc415d230 # v39.2.4
        with:
          configurationFile: .github/renovate.json5
          token: ${{ steps.generate-token.outputs.token }}
          renovate-version: "${{ env.WORKFLOW_RENOVATE_VERSION }}"
